FROM node:10.15.3

ENV PATH /usr/src/app/node_modules/.bin:$PATH
ADD ./ /usr/src/app
WORKDIR /usr/src/app

RUN npm install --only=dev
RUN npm install --silent

EXPOSE 3000
ENV CI=true
CMD [ "npm", "run", "start" ]